name: Generate and Publish Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'pom.xml'
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Generate documents
        run: ./mvnw --batch-mode
      - name: Setup git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Upload to Github Pages
        run: ./mvnw --batch-mode scm-publish:publish-scm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
