name: Generate and Publish Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Generate documents
      run: mvn --batch-mode

    - name: Upload to Github Pages
      run: mvn --batch-mode scm-publish:publish-scm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
